### ISSUE TITLE
Hyper `run` command isn't working on OSX: "failed to create container by docker"

### ISSUE THREAD

**Issue by chiefy** [hyperhq/hyper#28]
```bash
❯ hyper version && hyper images
The hyper version is 0.3
REPOSITORY     TAG                 IMAGE ID                           CREATED             VIRTUAL SIZE
puller         latest              100000000000                2015-07-17 18:01:13                 0 B
alpine         latest              31f630c65071                2015-06-12 15:38:15              5.0 MB

~
❯ hyper run --help
Usage:
  hyper run [OPTIONS] IMAGE [COMMAND] [ARG...]

create a pod, and launch a new VM to run the pod

Application Options:
  -p, --podfile=""       Create and Run a pod based on the pod file
  -k, --kubernetes=""    Create and Run a pod based on the kubernetes pod file
  -y, --yaml             Create a pod based on Yaml file
      --name=""          Assign a name to the container
      --attach           Attach the stdin, stdout and stderr to the container
      --workdir=""       Working directory inside the container
      --tty              Allocate a pseudo-TTY
      --cpu=1            CPU number for the VM
      --memory=128       Memory size (MB) for the VM
      --env=[]           Set environment variables
      --entrypoint=""    Overwrite the default ENTRYPOINT of the image
      --restart=""       Restart policy to apply when a container exits (never, onFailure, always)
      --rm               Automatically remove the pod when it exits

Help Options:
  -h, --help             Show this help message


~
❯ hyper run --attach alpine:latest /bin/ash
hyper ERROR: failed to create container by docker, No command specified

~
❯ uname -a
Darwin cnaje1ML1 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
```

**Comment by carmark** [comment]
Hello @chiefy ,

Really thanks for your trying `hyper` on Mac, I did reproduce this issue locally.  I think this should be a bug, since there is no default command in Docker official dockerfile.

```
FROM scratch
ADD rootfs.tar.gz /
```

I will try to fix this ASAP and provide a new binary.

Thanks again.
BR

**Comment by carmark** [comment]
Hi @chiefy ,

I fixed this issue, and did some unit test, it works well, you may check the following output:

```
lei@leis-MacBook-Pro:[~]$ hyper run --attach alpine /bin/ash
POD id is pod-BGPgUpQsjX
/ # ls
bin      dev      etc      home     lib      linuxrc  media    mnt      proc     root     run      sbin     sys      tmp      usr      var
/ # uname -a
Linux alpine-4805162867 4.0.4-hyper #81 SMP Tue Jul 28 19:10:58 CST 2015 x86_64 Linux
/ # echo $0
/bin/ash
/ #
```

You can download the latest binary from [here](http://hyper-install.s3.amazonaws.com/hyper-mac-bugfix-1.pkg)

Please let me know if you encounter any other problem with this new package.  I will do more test on this package and replace the old one later.

Thanks,

**Comment by chiefy** [comment]
Quick service @carmark , thanks! :+1:

**Comment by chiefy** [comment]
Installed the package, but it looks like the daemon is having issues w/ VirtualBox:

```
8/2/15 8:55:53.000 AM kernel[0]: org_virtualbox_SupDrvClient::initWithTask: Expected cookie 0x64726962 (VBoxSVC)
8/2/15 8:55:53.000 AM kernel[0]: org_virtualbox_SupDrvClient::initWithTask: Expected cookie 0x64726962 (VBoxHeadless)
8/2/15 8:55:53.000 AM kernel[0]: VBoxDrv: host_vmxon  -> vmx_use_count=1 rc=0
8/2/15 8:55:53.000 AM kernel[0]: VBoxDrv: host_vmxoff -> vmx_use_count=0
8/2/15 8:55:53.000 AM kernel[0]: vboxdrv: ffffff8238953020 VMMR0.r0
8/2/15 8:55:53.000 AM kernel[0]: vboxdrv: ffffff8238b4f020 VBoxDDR0.r0
8/2/15 8:55:53.000 AM kernel[0]: vboxdrv: ffffff81fe62a020 VBoxDD2R0.r0
8/2/15 8:55:54.000 AM kernel[0]: VBoxDrv: host_vmxon  -> vmx_use_count=1 rc=0
8/2/15 8:55:54.000 AM kernel[0]: VBoxDrv: host_vmxoff -> vmx_use_count=0
8/2/15 8:55:54.216 AM com.apple.launchd[1]: (sh.hyper.hyper) Throttling respawn: Will start in 10 seconds
```

**Comment by carmark** [comment]
Hello @chiefy ,

Thanks for your report, I also think it is a VirtualBox issue, could you please restart your system and run it again?  I did not encounter that before.

Regards,

**Comment by chiefy** [comment]
@carmark still having issue after restart:
```
8/3/15 9:57:22.000 AM kernel[0]: org_virtualbox_SupDrvClient::initWithTask: Expected cookie 0x64726962 (VBoxSVC)
8/3/15 9:57:22.000 AM kernel[0]: org_virtualbox_SupDrvClient::initWithTask: Expected cookie 0x64726962 (VBoxHeadless)
8/3/15 9:57:23.205 AM com.apple.launchd[1]: (sh.hyper.hyper) Throttling respawn: Will start in 10 seconds
```
Running boot2docker in VB, seems fine otherwise?

**Comment by carmark** [comment]
@chiefy 

I searched this error message and found it should be an issue in VirtualBox forum and checked the code of VirtualBox, I suppose it should init the state based on previous task.  I can not reproduce this issue, but you may try to run the following commands:
```
# launchctl unload /Library/LaunchDaemons/sh.hyper.hyper.plist
# vboxmanage unregistervm hyper-mac-pull-vm --delete
# rm -fr /var/lib/hyper/
```

Re-install the hyper package and try it again.

Regards,

**Comment by chiefy** [comment]
```bash
~
❯ hyper run --attach --rm alpine:latest /bin/ash
POD id is pod-ahmTVgyoJs
```
:beers:  thanks @carmark !
